### PR TITLE
Cleanup transition errors

### PR DESCRIPTION
**Pull request by derickl**

### CODE REVIEW

**Comment by derickl** [comment]
For the case I was solving for, we only had one active transition. What's the cleanest way to doing this? (just deleting the errors key seems like the simplest but probably at the expense of not sending that notification. _I could be wrong_).

@SCdF

**Comment by derickl** [comment]
I should probably add a caveat for cases where more than one sentinel transition works on a doc.

**Comment by SCdF** [comment]
@derickl I'm not sure what the right answer is sorry, I was just worried about that being too heavy handed to present as a general solution.

Honestly the best thing to do would probably be to write an api endpoint for it IMO (which you're welcome to do and submit a PR for btw!), then we can maintain the correctness of it as things progress (and in general it's better if the code changes data as opposed to scripts). However, I recognise there are downsides to that, including immediacy and complexity.

**Comment by garethbowen** [comment]
@derickl Is this still useful?

**Comment by derickl** [comment]
Probably long term @garethbowen.

**Comment by garethbowen** [comment]
@derickl Should it be fixed and merged or closed?

**Pull request closed without merging**
